books/urls.py
from django.conf.urls import url

from . import views

app_name = 'books'

urlpatterns = [
   # url(r'^$', views.index, name='index'),
   # url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),
   url(r'^$', views.IndexView.as_view(), name='index'),
   url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
   url(r'^book/add$', views.CreateView.as_view(), name='book-add'),
   url(r'^book/(?P<pk>[0-9]+)/$', views.UpdateView.as_view(), name='book-update'),
   url(r'^book/(?P<pk>[0-9]+)/delete/$', views.DeleteView.as_view(), name='book-delete'),

]

tlibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^$', RedirectView.as_view(url='/books/', permanent=True)),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

STORAGE_TYPE_CHOICES = (
    (2, "General"),
    (3, "Yandex"),
    (4, "Google"),
    (5, "RemoteStorage"),
    (1, "Unknown"),
)

COMPRESSOR_CHOICES = (
    (1, "Uncompressed"),
    (1, "7zip"),
    (3, "rar"),
    (4, "tgz"),
)

class Book(models.Model):
    old = models.BigIntegerField(help_text="old id",default=0)
    title = models.CharField(max_length=255, help_text="Title of books")
    author = models.CharField(max_length=255, help_text="authors")
    year = models.IntegerField(help_text="year")
    pages_count = models.IntegerField(help_text="number of pages", default=0)
    description = models.CharField(max_length=4000, help_text="Description")
    isbn = models.CharField(max_length=40, help_text="ISBN", default="")
    inserted = models.DateTimeField(default=timezone.now)

    # Metadata
    class Meta:
        ordering = ["title"]

    def __str__(self):
        """
        String for representing the MyModelName object (in Admin site etc.)
        """
        return self.title+" "+self.author

    def get_absolute_url(self):
        return reverse('book:detail', kwargs={'pk': self.pk})



class BookItem(models.Model):
    book_id = models.ForeignKey('Book',on_delete=models.CASCADE)
    file_format = models.CharField(max_length=10, help_text="Format of file pdf,djvu,doc,fb2...")
    file_size = models.IntegerField(help_text="Size of file in bytes")
    compressor = models.IntegerField(choices=COMPRESSOR_CHOICES, default=1, help_text="Compressor type")
    compressor_password = models.CharField(max_length=30, help_text="password on file")

    def __str__(self):
        """
        String for representing the MyModelName object (in Admin site etc.)
        """
        return self.file_format+" "+str(self.file_size)


class Storage(models.Model):
    name = models.CharField(max_length=10, help_text="Name of storage")
    type = models.IntegerField(choices=STORAGE_TYPE_CHOICES, default=1, help_text="Storage type")
    size = models.IntegerField(help_text="Size of storage in bytes", default=0)
    used = models.IntegerField(help_text="usage storage in bytes", default=0)
    available = models.BooleanField(help_text="status of avaliable",default=False)
    last_accessable = models.DateTimeField(help_text="Last used timestamp", default=None)

    def __str__(self):
        """
        String for representing the MyModelName object (in Admin site etc.)
        """
        return self.name + " ("+str(self.type)+")"


class BookItemPlace(models.Model):
    item_id = models.ForeignKey('BookItem',on_delete=models.CASCADE,)
    storage_id = models.ForeignKey('Storage',on_delete=models.CASCADE,)

books/views.py
from django.http import HttpResponse
from django.http import Http404
from .models import Book
from django.template import loader
from django.shortcuts import  render, get_object_or_404
# Create your views here.
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


class IndexView(generic.ListView):
    template_name = 'books/index.html'
    context_object_name = 'all_books'
    def get_queryset(self):
        return Book.objects.all()


class DetailView(generic.DetailView):
    model = Book
    template_name = 'books/detail.html'


class CreateView(CreateView):
    model = Book
    fields = ['title', 'author', 'year', 'pages_count', 'description', 'isbn']


class UpdateView(UpdateView):
    model = Book
    fields = ['title', 'author', 'year', 'pages_count', 'description', 'isbn']


class DeleteView(DeleteView):
    model = Book
    success_url = reverse_lazy('book:index')




# def index(request):
#     all_books = Book.objects.all()
#     template = loader.get_template('books/index.html')
#     context = {
#         'all_books': all_books,
#     }
#     return render(request,'books/index.html',context)
#
# def detail(request,book_id):
#     # try:
#     #     book = Book.objects.get(pk=book_id)
#     # except Book.DoesNotExist:
#     #     raise Http404("Book Does not exist")
#     book = get_object_or_404(Book, pk=book_id)
#     context = {'book': book}
#     return render(request, 'books/detail.html', context)

books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Tlibrary{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'books:index' %}">TLibrary</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'books:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Link1</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'books:index' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Link2</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'books:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'books:book-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add book
                    </a>
                </li>
                <li>
                    <a href="{% url 'books:index' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

books/templates/books/book_form.html
{% extends 'books/base.html' %}
{% block title %}add{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'books/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

books/templates/books/detail.html
{% extends 'books/base.html' %}

{% block title %}Details{% endblock %}

{% block body %}

<h2>{{ book.title }}</h2>

{% endblock %}

books/templates/books/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>

    </div>
{% endfor %}

books/templates/books/index.html
{% extends 'books/base.html' %}

{% block body %}
<ul>
{% for book in all_books %}
    <li><a href="{% url 'books:detail' book.id %}">{{ book.title }} {{ book.author }}</a></li>
{% endfor%}
</ul>
{% endblock %}